# This is a basic workflow to help you get started with Actions

name: Cert generator to docker registry

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: Build docker container
        run: docker build -t tigerframework/certgen .
      
      - name: Push image to docker
        run: docker push tigerframework/certgen


